
from PyQt5 import QtCore, QtGui, QtWidgets
from toolsource import *
import sys
class Ui_Dialog2(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        self.history = []  # 存储历史命令
        Dialog.resize(1104, 876)
        self.line_4 = QtWidgets.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(1080, 50, 16, 811))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(10, 50, 16, 811))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_6 = QtWidgets.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(20, 850, 1071, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_5 = QtWidgets.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(20, 40, 1071, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(30, 100, 93, 28))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(30, 140, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 260, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 460, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(30, 660, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(30, 300, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 340, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(30, 380, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(30, 420, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(30, 180, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(30, 540, 93, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 500, 93, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(30, 580, 93, 28))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 620, 93, 28))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(30, 220, 93, 28))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 700, 93, 28))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Dialog)
        self.pushButton_17.setGeometry(QtCore.QRect(30, 740, 93, 28))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Dialog)
        self.pushButton_18.setGeometry(QtCore.QRect(30, 780, 93, 28))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_20 = QtWidgets.QPushButton(Dialog)
        self.pushButton_20.setGeometry(QtCore.QRect(30, 60, 93, 28))
        self.pushButton_20.setObjectName("pushButton_20")
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setGeometry(QtCore.QRect(140, 160, 931, 691))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton_23 = QtWidgets.QPushButton(Dialog)
        self.pushButton_23.setGeometry(QtCore.QRect(860, 120, 101, 31))
        self.pushButton_23.setObjectName("pushButton_23")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 691, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_21 = QtWidgets.QPushButton(Dialog)
        self.pushButton_21.setGeometry(QtCore.QRect(970, 70, 101, 41))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Dialog)
        self.pushButton_22.setGeometry(QtCore.QRect(860, 70, 101, 41))
        self.pushButton_22.setObjectName("pushButton_22")
        self.textBrowser_2 = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser_2.setGeometry(QtCore.QRect(20, 50, 111, 801))
        self.textBrowser_2.setStyleSheet("background-color: rgb(138, 138, 138);")
        self.textBrowser_2.setObjectName("textBrowser_2")
        self.pushButton_19 = QtWidgets.QPushButton(Dialog)
        self.pushButton_19.setGeometry(QtCore.QRect(30, 820, 93, 28))
        self.pushButton_19.setObjectName("pushButton_19")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(140, 120, 691, 31))
        self.comboBox.setObjectName("comboBox")
        self.textBrowser_2.raise_()
        self.line_4.raise_()
        self.line_3.raise_()
        self.line_6.raise_()
        self.line_5.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.pushButton_4.raise_()
        self.pushButton_5.raise_()
        self.pushButton_6.raise_()
        self.pushButton_7.raise_()
        self.pushButton_8.raise_()
        self.pushButton_9.raise_()
        self.pushButton_10.raise_()
        self.pushButton_11.raise_()
        self.pushButton_12.raise_()
        self.pushButton_13.raise_()
        self.pushButton_14.raise_()
        self.pushButton_15.raise_()
        self.pushButton_16.raise_()
        self.pushButton_17.raise_()
        self.pushButton_18.raise_()
        self.pushButton_20.raise_()
        self.textBrowser.raise_()
        self.lineEdit.raise_()
        self.pushButton_21.raise_()
        self.pushButton_22.raise_()
        self.pushButton_19.raise_()
        self.pushButton_23.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def fill_command_from_combobox(self):
        # 获取被点击的命令并填充到 lineEdit 中
        command = self.comboBox.currentText()
        self.lineEdit.setText(command)

    def clear_command_history(self):
        # 清空命令历史列表
        self.history.clear()
        # 清空 comboBox 中的所有项目
        self.comboBox.clear()
        print("命令历史已清空")

    def remove_ansi_escape(self, text):
        # 使用正则表达式去掉 ANSI 转义字符
        ansi_escape = re.compile(r'\x1B(?:[@-Z\\-_]|\[[0-?]*[ -/]*[@-~])')
        return ansi_escape.sub('', text)
    def ansi_to_html(self, text):
        # 转换 ANSI 转义字符为 HTML 格式（例如，颜色）
        text = text.replace("\x1b[31m", "<font color='red'>")  # 例：红色
        text = text.replace("\x1b[32m", "<font color='green'>")  # 例：绿色
        text = text.replace("\x1b[33m", "<font color='yellow'>")  # 例：黄色
        text = text.replace("\x1b[34m", "<font color='blue'>")  # 例：蓝色
        text = text.replace("\x1b[0m", "</font>")  # 关闭颜色
        return text
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "burpsuite"))
        self.pushButton_2.setText(_translate("Dialog", "密探"))
        self.pushButton_3.setText(_translate("Dialog", "oneforall"))
        self.pushButton_4.setText(_translate("Dialog", "host碰撞"))
        self.pushButton_5.setText(_translate("Dialog", "jjjjjjs"))
        self.pushButton_6.setText(_translate("Dialog", "fuff"))
        self.pushButton_7.setText(_translate("Dialog", "ehole魔改"))
        self.pushButton_23.setText(_translate("Dialog", "清除历史记录"))
        self.pushButton_8.setText(_translate("Dialog", "httpx"))
        self.pushButton_9.setText(_translate("Dialog", "fscan"))
        self.pushButton_10.setText(_translate("Dialog", "cs"))
        self.pushButton_11.setText(_translate("Dialog", "API探测(1)"))
        self.pushButton_12.setText(_translate("Dialog", "sqlmap"))
        self.pushButton_13.setText(_translate("Dialog", "api文件夹"))
        self.pushButton_14.setText(_translate("Dialog", "packerfuzz"))
        self.pushButton_15.setText(_translate("Dialog", "Tscanplus"))
        self.pushButton_16.setText(_translate("Dialog", "goby"))
        self.pushButton_17.setText(_translate("Dialog", "nuclei"))
        self.pushButton_18.setText(_translate("Dialog", "PushButton"))
        self.pushButton_20.setText(_translate("Dialog", "使用指南"))
        self.pushButton_21.setText(_translate("Dialog", "刷新"))
        self.pushButton_22.setText(_translate("Dialog", "执行命令"))
        self.pushButton_19.setText(_translate("Dialog", "PushButton"))

        #函数连接
        self.pushButton.clicked.connect(lambda: run_burp(self))
        self.pushButton_2.clicked.connect(lambda: run_mitan(self))
        self.pushButton_10.clicked.connect(lambda: run_cs(self))
        self.pushButton_15.clicked.connect(lambda: run_Tscanplus(self))
        self.pushButton_3.clicked.connect(lambda: oneforall_command(self))
        self.pushButton_22.clicked.connect(lambda: execute_command(self))
        self.pushButton_21.clicked.connect(lambda: refresh_output(self))
        self.pushButton_6.clicked.connect(lambda: fuff_command(self))
        self.pushButton_8.clicked.connect(lambda: httpx_command(self))
        self.pushButton_5.clicked.connect(lambda: jjjjjjjs_command(self))
        self.pushButton_14.clicked.connect(lambda: packerfuzzer_command(self))
        self.pushButton_9.clicked.connect(lambda: fscan_command(self))
        self.pushButton_4.clicked.connect(lambda: hostp_command(self))
        self.pushButton_12.clicked.connect(lambda: sqlmap_command(self))
        self.pushButton_11.clicked.connect(lambda: api_command(self))
        self.pushButton_23.clicked.connect(self.clear_command_history)
        self.comboBox.activated.connect(self.fill_command_from_combobox)



